### ISSUE TITLE
SeveralSequencePerSpeciesException

### ISSUE THREAD

**Issue by sgarciah12** [DessimozLab/f1000_PhylogeneticTree#1]
Hello,

I am building a species tree from 164 bacterial species and am having issues applying the protocol described in https://f1000research.com/articles/9-511, in particular when using the python script named "filter_groups.py".

When I try to filter the OrthologousGroupsFasta folder using the script, I get the following error:

```
srun python3 filter_groups.py --min-nr-species 130 --input OMA.2.5.0/Output/OrthologousGroupsFasta/ --output COGs_for_tree/

srun: job 96677 queued and waiting for resources
srun: job 96677 has been allocated resources

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "filter_groups.py", line 32, in convert_fasta_file
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 32, in <listcomp>
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 26, in convert_id_to_species_name
    raise SeveralSequencePerSpeciesException("Species \"{}\" seen more than once in {}"
SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG7343.fa
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "filter_groups.py", line 104, in <module>
    convert_files(conf.input, conf.output, conf.min_nr_species, pattern=conf.ext, nr_processes=conf.threads)
  File "filter_groups.py", line 56, in convert_files
    result = mp.starmap(convert_fasta_file, args_iter)
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
__main__.SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG7343.fa
srun: error: maestro-1039: task 0: Exited with exit code 1
```

I made sure that all my species have a different name in the genomes of the DB folder of OMA before running it. I also checked with a different `--min-nr-species` number and I get the same error but in different OGs files. So I don't understand, is it because I am using python3 instead of python2?

Thank you for your help!

Best regards

**Comment by alpae** [comment]
Hi @sgarciah12 

the `filter_groups.py` script extracts the species name from the fasta header, i.e. the part that is in square brackets. This is a common standard for fasta files from several sources. However, if your source does not contain such a label or you include several genomes from the same species, you might run into this problem.  
It would be helpful if you could post the file that raises this problem. Alternatively, you could change the regular expression in https://github.com/DessimozLab/f1000_PhylogeneticTree/blob/cd68e7a113f99ff97e7b35eca2459d1ed2932393/filter_groups.py#L11 in a way that identifies your species uniquely.

**Comment by sgarciah12** [comment]
Hi @alpae,

Thank you for your quick answer.

I made sure that the 164 genomes were from different species and they were named differently. However, when I check the FASTA headers I find that OMA added two different "between-brackets" species names when generating the OG file. That is, a first one with the "original" species name (some of which are not well classified) and a second one with my annotation (the correct one). See, for example, in OG7343:

```
>WP_026131228.1 MULTISPECIES: hypothetical protein [Leptospira] [Leptospira_abararensis]
MKVMKSIFILLAVLGLNLSVLAQQNNQGGNQQANEAVEKIDELLKGELVPEDDDKNLTEEQKRRKKAIQEQEALWKNPDF
KGYDKNFQELHQLSKAFANNKFRLALSNYQSGVNTVLKMRESVEQYRKEEAEKKRLDEKWYWQKVDRKAREDRVVSREKL
VAKQQALNYFTKAINHLDEIKNPDLRERPEFKRLLSDTYRSWILTEYDLQNLPQCIPILELYIEIDENEKEYPAHKYLAS
CYAFEENMIKKYGGASEDQMFKYRYKKNVHLLRATELKYGKDSPEYKHIVNLVNKDEVISVRP

>WP_026131228.1 MULTISPECIES: hypothetical protein [Leptospira] [Leptospira_adleri]
MKVMKSIFILLAVLGLNLSVLAQQNNQGGNQQANEAVEKIDELLKGELVPEDDDKNLTEEQKRRKKAIQEQEALWKNPDF
KGYDKNFQELHQLSKAFANNKFRLALSNYQSGVNTVLKMRESVEQYRKEEAEKKRLDEKWYWQKVDRKAREDRVVSREKL
VAKQQALNYFTKAINHLDEIKNPDLRERPEFKRLLSDTYRSWILTEYDLQNLPQCIPILELYIEIDENEKEYPAHKYLAS
CYAFEENMIKKYGGASEDQMFKYRYKKNVHLLRATELKYGKDSPEYKHIVNLVNKDEVISVRP
```
I checked and it seems that the regex expression might be the issue, yes, since it captures the first occurrence and not the second.

![image](https://user-images.githubusercontent.com/91054260/157007283-4bf10f1b-0b2d-4732-84f2-42563178a211.png)

Do you have any idea on how to make the regex function call "species" to the second occurrence and not the first?

Find attached the conflictive OG7343.fa in case you want to explore it but this is also happening with other files in the generated OGs.

Thank you for your time,

Best regards

Samuel

[OG7343.fa.txt](https://github.com/DessimozLab/f1000_PhylogeneticTree/files/8196651/OG7343.fa.txt)

**Comment by alpae** [comment]
you could for example use this regex: 

    r"\[(?P<species>[^]]*)\][^]]*"

this would disallow any closing square bracket after the species match.

Cheers Adrian

**Comment by alpae** [comment]
sorry, closed it quite quickly, feel free to reopen if it doesn't work or there's another issue

**Comment by sgarciah12** [comment]
Hi,

Yes, it doesn't work, sorry.

I tried with your option editing `filter_groups.py` to `RE_SPECIES = re.compile("\[(?P<species>[^]]*)\][^]]*")` and I get the same error message:

```
srun python3 filter_groups.py --min-nr-species 155 --input OMA.2.5.0/Output/OrthologousGroupsFasta/ --output COGs_for_tree/
srun: job 1266340 queued and waiting for resources
srun: job 1266340 has been allocated resources
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "filter_groups.py", line 32, in convert_fasta_file
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 32, in <listcomp>
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 26, in convert_id_to_species_name
    raise SeveralSequencePerSpeciesException("Species \"{}\" seen more than once in {}"
SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG7343.fa
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "filter_groups.py", line 104, in <module>
    convert_files(conf.input, conf.output, conf.min_nr_species, pattern=conf.ext, nr_processes=conf.threads)
  File "filter_groups.py", line 56, in convert_files
    result = mp.starmap(convert_fasta_file, args_iter)
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
__main__.SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG7343.fa
srun: error: maestro-1039: task 0: Exited with exit code 1
```

I have also tried with the expression `\[[^]]*\].*?\[(?P<species>[^]]*)\]` that is supposed to assign "species" only to the second group and I get a very similar error, this time with a different OG (OG10394.fa) that I am attaching at the end.

![image](https://user-images.githubusercontent.com/91054260/157032421-fbad18d8-3013-40d3-9b3a-4b5f23848c55.png)

Error message:

```
srun python3 filter_groups.py --min-nr-species 155 --input OMA.2.5.0/Output/OrthologousGroupsFasta/ --output COGs_for_tree/
srun: job 1266234 queued and waiting for resources
srun: job 1266234 has been allocated resources
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "filter_groups.py", line 32, in convert_fasta_file
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 32, in <listcomp>
    records = [convert_id_to_species_name(z) for z in Bio.SeqIO.parse(infile, 'fasta')]
  File "filter_groups.py", line 26, in convert_id_to_species_name
    raise SeveralSequencePerSpeciesException("Species \"{}\" seen more than once in {}"
SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG10394.fa
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "filter_groups.py", line 104, in <module>
    convert_files(conf.input, conf.output, conf.min_nr_species, pattern=conf.ext, nr_processes=conf.threads)
  File "filter_groups.py", line 56, in convert_files
    result = mp.starmap(convert_fasta_file, args_iter)
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/gensoft/exe/Python/3.8.3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
__main__.SeveralSequencePerSpeciesException: Species "Leptospira" seen more than once in OMA.2.5.0/Output/OrthologousGroupsFasta/OG10394.fa
srun: error: maestro-1039: task 0: Exited with exit code 1
```

[OG10394.fa.txt](https://github.com/DessimozLab/f1000_PhylogeneticTree/files/8197584/OG10394.fa.txt)

Any idea on how to sort that out?

Thank you again for your time!

**Comment by alpae** [comment]
Hi @sgarciah12 

sorry, that regex was actually really not good, it was missing the line-end token. the following regex works for me on your example:

    RE_SPECIES = re.compile(r"\[(?P<species>[^]]*)\][^]]*$")

Best wishes
Adrian

**Comment by sgarciah12** [comment]
Thanks @alpae ! Now it works perfectly fine!
